logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.dashboard]
    address = ":8080"
  [entryPoints.http]
  address = ":80"

[api]
entrypoint="dashboard"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = ""
watch = true
network = "manually_creted_docker_proxynet"
